### Get Orders
GET http://localhost:4004/odata/v4/manage-orders/Orders

### Get Order
GET http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')

### Create Order
POST http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "client5@client5.com",
    "FirstName": "Lorena",
    "LastName": "Garcia",
    "CreatedOn": "2024-08-11"
}

### Update Order
PUT http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com') HTTP/1.1
Content-Type: application/json

{
   "FirstName": "FirstName Updated",
   "LastName": "LastName Updated"
}

### Delete Order
DELETE http://localhost:4004/odata/v4/manage-orders/Orders('client5@client5.com')

### Get Customer Rate - Function
GET http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(clientEmail='client2@client2.com')